### ISSUE TITLE
undefined method `negative?' for "3599":String

### ISSUE THREAD

**Issue by ken-muturi** [gathuku/mpesa#29]
undefined method `negative?' for "3599":String; **Rails 7.1 and  ruby 3.2.2**

![image](https://github.com/gathuku/mpesa/assets/3158605/965a1e11-ba8c-4e67-ade6-452a5b02c16f)

![image](https://github.com/gathuku/mpesa/assets/3158605/5b08de93-dada-4f04-8511-a55dfab457ac)

**Comment by gathuku** [comment]
Can you provide more information about this issue and how to reproduce?

**Comment by ken-muturi** [comment]
@gathuku I just installed the gem and tried to use it as outlined on the screenshots above.  I am trying to use the response from  a call to  Mpesa::Client.new . The response  client.auth gives me this error.  I am on Rails 7.1 and ruby 3.2.2   . I have just tried to mpesa credentials this on vanilla rails and it works;  ** i would love to have the gem working though ** 
![image](https://github.com/gathuku/mpesa/assets/3158605/80c6dc58-b582-414e-8d5d-9f5036779eb6)

**Comment by gathuku** [comment]
@ken-muturi  I have fixed the issue can you try this version https://github.com/gathuku/mpesa/releases/tag/v0.3.5 and see how it goes.

**Comment by ken-muturi** [comment]
let me review and revert. thanks pal for the effort though
